karma_diving_V2/site/karma/booking/urls.py
#booking URLS.PY
from django.conf.urls import url
from . import views

app_name ='booking'

urlpatterns =[

    url(r'^new/$',views.CreateClientView.as_view(), name='create'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    #joe est une limace slugify==> joe-est-une-limace

]

karma_diving_V2/site/karma/karma/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^booking/', include('booking.urls',namespace='booking')),
    url(r'^booking/', include('django.contrib.auth.urls')),
]

karma_diving_V2/site/karma/booking/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.forms import ModelForm
#Create your models here.
SEX_CHOICES = (
    ('Male','M'),
    ('Female','F')
)


ACTIVITY_CHOICE = (
    ('Yoga','Yoga'),
    ('Pilate','Pilate'),
    ('Plongée','Plongée')
)

class Produit(models.Model):
    titre = models.CharField(max_length=256)
    categorie = models.CharField(max_length=256)
    prix = models.PositiveIntegerField()
    prix_special = models.PositiveIntegerField()
    nbr_place = models.PositiveIntegerField()

    def __str__(self):
        return self.titre

class Client(models.Model):

    prenom = models.CharField(max_length=256)
    nom_famille = models.CharField(max_length=256)
    date_birth = models.DateField()
    sexe = models.CharField(max_length=10,choices=SEX_CHOICES)
    nationalite = models.CharField(max_length=256)
    email_adresse = models.CharField(max_length=256)
    facebook = models.CharField(max_length=256)
    arrivee_date = models.DateField()
    depart_date = models.DateField()
    produit = models.ForeignKey(Produit,default='null')
    # ,choices=ACTIVITY_CHOICE,default='null')
    # product = forms.MultipleChoiceField(choices=CHOICES, widget=forms.CheckboxSelectMultiple())

    def __str__(self):
        return self.prenom + ' ' + self.nom_famille


    def get_absolute_url(self):
        return reverse('booking:thanks')

karma_diving_V2/site/karma/booking/forms.py
from django.contrib.auth import get_user_model
from booking.models import Client
from django.contrib.auth.forms import UserCreationForm
from django import forms

CHOICES = (
        ('a','yoga'),
        ('b','plongee'),
        ('c','snorkling'),
)

class ClientForm(forms.ModelForm):

    class Meta():
        model = Client

        fields = ('prenom','nom_famille','date_birth','sexe','email_adresse','arrivee_date','depart_date','produit')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['prenom'].label = 'yoshi client name'
        self.fields['nom_famille'].label = 'yoshi nom de famille here'

karma_diving_V2/site/karma/booking/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from booking.forms import ClientForm
from booking.models import Client
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
class CreateClientView(CreateView):
    login_url = '/booking/'
    redirect_field_name = 'index.html'
    form_class = ClientForm
    model = Client

# def add_comment_to_post(request, pk):
#     client = get_object_or_404(Client, pk=pk)
#     if request.method == "POST":
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             booking = form.save(commit=False)
#             booking.client = client
#             booking.save()
#             return redirect('index.html')
#     else:
#         form = ClientForm()
#     return render(request, 'index.html', {'form': form})
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class ThanksPage(TemplateView):
    template_name = 'thanks.html'

karma_diving_V2/site/karma/karma/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

karma_diving_V2/site/karma/booking/templates/booking/booking_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>

</div>

{% endblock %}

karma_diving_V2/site/karma/booking/templates/booking/client_form.html
{%extends "booking/booking_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Reservez avec Yoshi !</h4>

<form  action="{% url 'booking:create' %}" method="post" id="ClientForm">
  {% csrf_token %}
  {% bootstrap_form form%}
  <!-- <div class="form-group">
  <label for="produit">selectionnez un produit</label>
  <select class="form-control" name="produit" id="produit" >
    <option>plongée</option>
    <option>snorkling</option>
    <option>openwater</option>
    <option>yoga</option>
    <option>apnée</option>
  </select>
</div> -->
  <input type="submit" class="btn btn-primary btn-large" value="Reserver">
</form>

{% endblock %}

karma_diving_V2/site/karma/booking/templates/booking/thanks.html
{%extends "booking/booking_base.html" %}

{% block group_content %}
<h1>Thanks for booking! booking page!</h1>
{% endblock %}

karma_diving_V2/site/karma/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Karma !</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">


    <!-- Font ecritures -->
    <!-- https://fonts.google.com/ -->
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Source+Serif+Pro" rel="stylesheet">

  </head>
  <body class ="loader">
    <!-- navBAR on peut rajouter des classes customiser dans la catégorie nav bar -->
    <nav class="navbar navbar-default techfont custom-navbar">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class='navbar-brand bigbrand' href="{% url 'home' %}">Karma !</a>
          <li><a href="#">About</a></li>
          <li><a href="https://www.github.com">Github</a></li>
          <li><a href="https://www.linkedin.com">LinkediIn</a></li>
          <li><a href="https://www.jeuxvideo.com">Etajv</a></li>
        </ul>


        <ul class='nav navbar-nav navbar-right'>

            <li><a class='nav navbar-nav navbar-right' href="{% url 'booking:create' %}"><span class='glyphicon glyphicon-shopping-cart'></span> </a></li>


          
        </ul>

      </div>

    </nav>

  <!-- Content block -->
  <div class="content container">
    <div class="row">
      <div class="col-md-8">
        <div class="blog_posts">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>

  </body>
</html>

karma_diving_V2/site/karma/templates/index.html
{% extends 'base.html' %}
{% block content%}
    <h1>Welcome to Karma diving !</h1>
{% endblock %}

karma_diving_V2/site/karma/templates/thanks.html
{%extends "booking/booking_base.html" %}

{% block group_content %}
<h1>Thanks for booking! Come back soon!</h1>
{% endblock %}